name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  api-key:
    required: true
    description: 'API Key value of Mackerel. Should be stored in GitHub Secrets.'
  title:
    required: true
    description: 'Annotation title'
  description:
    required: false
    description: '[optional] Annotation details'
  from:
    required: false
    description: 'Starting time (epoch seconds)'
  to:
    required: false
    description: 'Ending time (epoch seconds)'
  service:
    required: true
    description: 'Service name'
  roles:
    required: false
    description: '[optional] Role name array (omit this field to register an annotation related to the service)'
runs:
  using: 'node16'
  main: 'dist/index.js'
